### PR TITLE
Fix typos in README

### PR DESCRIPTION
**Pull request by Twoomatch**

### CODE REVIEW

**Review by chenxiaolong — APPROVED** [review]

**Comment by chenxiaolong** [comment]
Thank you. Not sure how I managed to typo that four times without even using copy/paste.

**Comment by dunsany** [comment]
Autocompletion? :-)

**Comment by Twoomatch** [comment]
Word completion, maybe? :-)

**Comment by chenxiaolong** [comment]
Just tested it, you're absolutely right :) Time to disable that in my editor.

**Pull request merged**
