### PR TITLE
Add vibrate setting on start stop recording

### PR DESCRIPTION
**Pull request by quyenvsp**

### CODE REVIEW

**Comment by chenxiaolong** [comment]
Thanks for the PR!

I like the idea, but would prefer to take a different approach that doesn't require new permissions. With PR #169, BCR now shows a notification when recording completes. It should be possible to have similar behavior by turning on the vibration option in Android's settings for BCR's `Background services` and `Success alerts` notifications. Is that a good enough solution for what you want to do?

**Comment by quyenvsp** [comment]
Yeah I know it and is first thing tried, but no idea why that way not working on my Px5a.

add NotificationChannel vibrateEnable vibratePattern, set IMPORTANCE_HIGH, uninstall module then re-install, allow notification bypass do not disturb....nothing can make notification vibrate work.
Even call notificationManager.notify in SettingsActivity worked, but not when calling.

About "doesn't require new permissions", android.permission.VIBRATE need on all ways, this permission dont need ask users, so I think it is ok.

**Comment by chenxiaolong** [comment]
Interesting. I thought it was working properly because my smartwatch vibrated, but after disconnecting my watch, I can reproduce the problem on my Pixel 7 Pro.

Can you give #171 a try? It uses the vibrator service, similar to this PR, except instead of adding a new setting, it just uses the notification channel's vibration setting.

**Comment by quyenvsp** [comment]
Nice, it surely better if use notification setting, will test it on my device soon 👍

**Pull request closed without merging**
