### PR TITLE
Russiano #2

### PR DESCRIPTION
**Pull request by bogachenko**
Tell me, is it possible to combine these 2 lines with this 1 argument?

Now
`<string name="output_dir_bottom_sheet_filename_template">Шаблон имени файла</string>`
`<string name="filename_template_dialog_title">Шаблон имени файла</string>`

After
`<string name="output_dir_bottom_sheet_filename_template">Шаблон имени файла</string>`
`<string name="filename_template_dialog_title">@string/output_dir_bottom_sheet_filename_template</string>`

Or is it not possible to do this for the title?

### CODE REVIEW

**Comment by chenxiaolong** [comment]
> After
> `<string name="output_dir_bottom_sheet_filename_template">Шаблон имени файла</string>`
> `<string name="filename_template_dialog_title">@string/output_dir_bottom_sheet_filename_template</string>`
>
> Or is it not possible to do this for the title?

Yes, that should be perfectly fine.

**Comment by chenxiaolong** [comment]
It looks like commit 13b51f3b9f66c8ac53af7060cb7c413f2a96d1b7 reformatted the file. I have 2 small concerns about this:

* The indentation changed from 4 spaces to 1 tab character. Please leave it at 4 spaces to match the rest of the project.
* The strings that contain `<annotation>` got split into multiple lines. Please avoid doing that because when the ending `</string>` is on its own line, it results in the translation having an extra space at the end.

**Comment by bogachenko** [comment]
>The indentation changed from 4 spaces to 1 tab character. Please leave it at 4 spaces to match the rest of the project.

I don't want to argue about tabs versus spaces (_this is your repository and the rules are yours, and for the machine, the markup between these two positions is not particularly important_), but don't you think tabs are better and should be entered for other languages? 1 tab (8 spaces) this is 1 kb, while 1 space is 1 kb (respectively, this is 4 kb for you).

eg. your ENG language file has the size: 6.68 KB, but if you remove the spaces and leave the tabs, you can compress the file to a size of 6.45 KB.

In any case, you have the last word, should I give it back?

**Comment by chenxiaolong** [comment]
I can see that point of view, though I'd still prefer 4 spaces for consistency. (Once it's compiled into the `.apk`, there's no longer a size difference. It gets converted into a binary XML format that has no indentation.)

**Comment by bogachenko** [comment]
Brought it back.

**Review by chenxiaolong — APPROVED** [review]

**Pull request merged**
