### PR TITLE
Introduce new string templating engine

### PR DESCRIPTION
**Pull request by chenxiaolong**
This fully replaces the old `bcr.properties` templating system and the existing configuration will be automatically migrated during app startup.

Improvements over the original templating system:

* No longer a hidden, unsupported feature
* No need to manually create and edit config files
* Much more ergonomic syntax
* Supports multiple fallbacks (eg. `[{contact_name}|{caller_name}|Unknown]`)
* Supports nested fallbacks (eg. `{date}[ ([{contact_name}|Unknown])|]`)
* Supports the file retention feature as long as the date is at the beginning of the template or is preceded by a literal string
* UI option has syntax highlighting

Fixes: #288

---

dark mode output settings screenshot light mode output settings screenshot
dark mode filename template screenshot light mode filename template screenshot

### CODE REVIEW

**Comment by blackwind** [comment]
I feel like there are few enough variables, and that they're self-explanatory enough, that they could all be displayed in the popup and one could figure it out entirely without checking the documentation (which should still be linked just in case).

**Comment by chenxiaolong** [comment]
Yeah, that seems reasonable. I'll see if I can add a "known variables" list in there.

**Comment by chenxiaolong** [comment]
How about this?


dark mode filename template dialog screenshot with list of supported variables added

**Comment by blackwind** [comment]
Perfect. 👍

**Pull request merged**
